version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  web:
    build: .
    env_file: ./.env
    command: npm run start
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis
    links:
      - redis
    depends_on:
      - redis
